const ANIMALS = [
  {
    id: "rabbit",
    name: "小兔子",
    nameEn: "Rabbit",
    emoji: "🐰",
    category: "mammal",
    habitat: ["草原", "森林", "家庭"],
    facts: [
      "兔子的耳朵不仅能听声音，还能帮它散热降温哦！",
      "兔子开心到飞起时会在空中扭一下身子，这个动作叫 binky。",
      "兔子其实不太喜欢被抱起来，四脚离地会让它紧张。",
    ],
    image: "",
    soundUrl: "",
  },
  {
    id: "cat",
    name: "喵喵猫",
    nameEn: "Cat",
    emoji: "🐱",
    category: "mammal",
    habitat: ["家庭", "城市"],
    facts: [
      "猫咪的呼噜声既能表达开心，也能在受伤时自我疗愈。",
      "猫每天要睡 12 到 16 个小时，是名副其实的睡觉冠军。",
      "猫的舌头长满倒刺，舔毛的时候就像一把小梳子。",
    ],
    image: "",
    soundUrl: "",
  },
  {
    id: "dog",
    name: "汪汪狗",
    nameEn: "Dog",
    emoji: "🐶",
    category: "mammal",
    habitat: ["家庭", "城市", "草原"],
    facts: [
      "狗狗的鼻纹就像人的指纹一样，每一只都独一无二。",
      "狗的嗅觉细胞数量是人类的几十倍，能闻出我们察觉不到的气味。",
      "狗摇尾巴的方向和幅度不同，代表的心情也不一样哦。",
    ],
    image: "",
    soundUrl: "",
  },
  {
    id: "panda",
    name: "大熊猫",
    nameEn: "Giant Panda",
    emoji: "🐼",
    category: "mammal",
    habitat: ["山地森林", "竹林"],
    facts: [
      "熊猫每天要吃掉十几公斤竹子，所以大部分时间都在吃和睡。",
      "大熊猫宝宝出生时只有约 100 克，还不到妈妈体重的千分之一。",
      "大熊猫的前掌有六个手指，多出来的“伪拇指”专门用来抓竹子。",
    ],
    image: "",
    soundUrl: "",
    conservation: "易危 VU",
  },
  {
    id: "fox",
    name: "小狐狸",
    nameEn: "Red Fox",
    emoji: "🦊",
    category: "mammal",
    habitat: ["森林", "草原", "城市近郊"],
    facts: [
      "狐狸会用自己的大尾巴在睡觉时盖住鼻子保暖，超可爱！",
      "狐狸的耳朵非常灵，能听见雪层下面田鼠活动的声音。",
      "红狐是世界上分布最广的野生犬科动物。",
    ],
    image: "",
    soundUrl: "",
  },
  {
    id: "koala",
    name: "考拉",
    nameEn: "Koala",
    emoji: "🐨",
    category: "mammal",
    habitat: ["森林", "桉树林"],
    facts: [
      "考拉几乎整天都在睡觉，一天能睡 18 到 22 个小时。",
      "考拉很少喝水，身体需要的水分大多来自桉树叶。",
      "“Koala”这个名字在原住民语言里的意思就是“不喝水”。",
    ],
    image: "",
    soundUrl: "",
    conservation: "濒危 EN",
  },
  {
    id: "penguin",
    name: "小企鹅",
    nameEn: "Penguin",
    emoji: "🐧",
    category: "bird",
    habitat: ["极地冰川", "海岸", "海洋"],
    facts: [
      "企鹅爸爸会把蛋放在脚背上孵化，走路一摇一摆超萌。",
      "企鹅并不是都住在南极，有的企鹅就生活在温暖的赤道附近。",
      "企鹅的骨头比多数会飞的鸟更实心，能帮它轻松潜入深海。",
    ],
    image: "",
    soundUrl: "",
  },
  {
    id: "tiger",
    name: "小老虎",
    nameEn: "Tiger",
    emoji: "🐯",
    category: "mammal",
    habitat: ["森林", "山地", "湿地"],
    facts: [
      "每只老虎身上的条纹都不同，就像它们的专属身份证。",
      "老虎的条纹不只长在毛发上，剃掉毛皮肤上也有花纹。",
      "老虎是天生的游泳健将，天热时喜欢泡在水里乘凉。",
    ],
    image: "",
    soundUrl: "",
    conservation: "濒危 EN",
  },
  {
    id: "lion",
    name: "小狮子",
    nameEn: "Lion",
    emoji: "🦁",
    category: "mammal",
    habitat: ["稀树草原", "草原"],
    facts: [
      "狮子打哈欠其实常常是在告诉同伴：我有点紧张啦。",
      "狮子的吼声可以传到 8 公里以外，是草原上最响亮的嗓门。",
      "狮子是唯一喜欢群居的大型猫科动物。",
    ],
    image: "",
    soundUrl: "",
    conservation: "易危 VU",
  },
  {
    id: "frog",
    name: "小青蛙",
    nameEn: "Frog",
    emoji: "🐸",
    category: "amphibian",
    habitat: ["湿地", "池塘", "雨林"],
    facts: [
      "有些青蛙闭上眼睛是因为它们的眼皮是透明的，还能看见哦。",
      "青蛙不光用肺呼吸，皮肤也能帮忙呼吸，所以要一直保持湿润。",
      "青蛙一跳能达到自己身长的 20 倍以上。",
    ],
    image: "",
    soundUrl: "",
  },
  {
    id: "turtle",
    name: "小乌龟",
    nameEn: "Turtle",
    emoji: "🐢",
    category: "reptile",
    habitat: ["淡水域", "海洋", "湿地"],
    facts: [
      "乌龟的龟壳其实是它身体的一部分，和骨头连在一起呢。",
      "有些乌龟可以用泄殖腔辅助呼吸，让自己在水下待得更久。",
      "乌龟非常长寿，有些个体能活过 150 年。",
    ],
    image: "",
    soundUrl: "",
  },
  {
    id: "hamster",
    name: "小仓鼠",
    nameEn: "Hamster",
    emoji: "🐹",
    category: "mammal",
    habitat: ["草原", "农田", "地下洞穴"],
    facts: [
      "仓鼠会把食物塞进腮帮子里，鼓鼓的像个小口袋。",
      "仓鼠的颊囊一直延伸到肩膀，能装下差不多和自己一样重的食物。",
      "仓鼠喜欢独居，成年后最好一只一笼单独饲养。",
    ],
    image: "",
    soundUrl: "",
  },
];
